name: CI

on:
  push:
jobs:
  ci_validation:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      ACCEPT_HMAC_SECRET: "ACCEPT_HMAC_SECRET"
      IFRAME_ID: "IFRAME_ID"
    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0
          # bundler-cache: true
          # cache-version: 1

      - name: Bundler install
        run: bundle install
  
      - name: Test
        run: |
          bundle exec rake db:create
          bundle exec rake db:migrate
          bundle exec rspec .
        env:
          ACCEPT_HMAC_SECRET: "ACCEPT_HMAC_SECRET"
          IFRAME_ID: "IFRAME_ID"

      - name: Lint
        run: bundle exec rubocop